In [2]:
# --- 0) Imports & paths ---
import pandas as pd
import numpy as np

In [3]:
%load_ext autoreload
%autoreload 2

In [4]:
citeseq = pd.read_csv('k_ablation_citeseq.csv', index_col=0)
citeseq

,Dataset,Adjusted_Rand_Index,Mean_LISI_Score,Mean_Silhouette_Score,Silhouette_Benchmark,V_Measure
Folder,,,,,,
10d,Denoised,0.7185,8.0453,0.5535,-0.0988,0.7708
10d,True,0.5925,8.4578,0.5007,-0.0362,0.7070
15d,Denoised,0.7159,6.9634,0.6296,0.0295,0.7792
15d,True,0.7244,7.4046,0.5277,0.0298,0.7793
20d,Denoised,0.7560,6.8079,0.5591,0.0630,0.7881
20d,True,0.7163,6.6117,0.4904,0.0842,0.7650
50d,Denoised,0.8282,5.8349,0.5089,0.0877,0.8237
50d,True,0.6708,5.8726,0.6289,0.0995,0.7433
5d,Denoised,0.6050,11.1725,0.5603,-0.1052,0.6810
5d,True,0.5067,10.4220,0.6651,-0.0718,0.6528

In [6]:
neo_cortex = pd.read_csv('k_ablation_neocortex.csv', index_col=0)
neo_cortex

,Dataset,Adjusted_Rand_Index,Mean_LISI_Score,Mean_Silhouette_Score,Silhouette_Benchmark,V_Measure
Folder,,,,,,
100d,Denoised,0.4259,6.3095,0.4377,0.0273,0.5472
100d,True,0.3369,6.0869,0.3844,0.0605,0.5224
10d,Denoised,0.3649,6.1185,0.4080,0.1087,0.5302
10d,True,0.3222,5.6981,0.4151,0.1016,0.5288
15d,Denoised,0.3926,5.6644,0.3954,0.1279,0.5592
15d,True,0.3080,5.3908,0.4291,0.0356,0.5059
200d,Denoised,0.3675,6.5765,0.3899,0.1228,0.5498
200d,True,0.3382,6.6067,0.3600,0.0630,0.5261
20d,Denoised,0.3955,5.6552,0.4311,0.1179,0.5550
20d,True,0.3981,5.5292,0.4310,0.1007,0.5451
25d,Denoised,0.3811,5.8504,0.4199,0.1256,0.5743
25d,True,0.3456,5.5712,0.4409,0.1011,0.5161
50d,Denoised,0.4225,6.2214,0.3619,0.1477,0.5533
50d,True,0.3524,5.8046,0.4112,0.0510,0.5292
5d,Denoised,0.3355,7.8803,0.3931,0.0102,0.4977
5d,True,0.3201,7.3267,0.4200,0.0375,0.4906